### ISSUE TITLE
state is undefined

### ISSUE THREAD

**Issue by LopatkinEvgeniy** [erikras/multireducer#105]
I have some reducer: 

```
export default function someReducer (state = initState, action) {
  switch (action.type) {
    ....
  }
}
```

When i use it with multireducer there is error because action is undefined when multireducer initialize;
To fix it i write that: 

```
export default function someReducer (state = initState, action) {
if (!action) return state;

....
}
```

or that:

```
export default function someReducer (state = initState, action = {}) {
  ...
}
```

**Comment by jsdmc** [comment]
@LopatkinEvgeniy I prefer to set default action like in your example above. 
Redux dispatches INIT action when app starts. Since we don't rely on that action and call reducer manually to calculate initial state for multireducer - here your bug comes in. Will fix that.
