### ISSUE TITLE
WIth immutable

### ISSUE THREAD

**Issue by danosaure** [erikras/multireducer#107]
If I have a full immutable state, this is not working.

**Comment by yesmeck** [comment]
Hello, I'm working on a [new version](https://github.com/erikras/multireducer/releases) of `multireducer`, and it supports immutable.js, could you give it a try?

**Comment by danosaure** [comment]
Sorry, I am no more working on this as it was not working.

**Comment by thecaddy** [comment]
I am revisiting this lib since ive been using immutable for a while and it wasn't available until now.  It works great in beta3, only comment I have is to expose the library and add a bit of docs around it.

```
import multireducer from 'multireducer/lib/immutableMultireducer'
```
to
```
import {immutableMultireducer} from 'multireducer'
```

**Comment by yesmeck** [comment]
@thecaddy Just `import multireducer  from 'multireducer/immutable'`;

**Comment by thecaddy** [comment]
even better, thanks for the awesome work.

**Comment by yesmeck** [comment]
As [v3.0.0](https://github.com/erikras/multireducer/releases/tag/v3.0.0) released, I'm closing this issue, feel free to reopen this issue if you have any questions.
