### ISSUE TITLE
Store multireducer key in context

### ISSUE THREAD

**Issue by me6iaton** [erikras/multireducer#112]
One of the options - store multireducer key in react context, here is my experiment for this 
https://github.com/me6iaton/multireducer/commit/a15f58620580d254e6197c34a493c64055e95f67

**Comment by yesmeck** [comment]
What's the benefit to store reducer key in context?

**Comment by me6iaton** [comment]
config reducer key in root router component, once, and use connectMultireducer in deep components with the same key

**Comment by yesmeck** [comment]
Seems your commit is based on the version 2, `connectMultireducer ` has been removed in version 3. If you want pass reducer key down to the child components, you can create context by yourself in version 3:

```javascript
class ListComponent extends Component {
  static propTypes = {
    as: PropTypes.string.isRequired
  }

  static childContextTypes = {
    as: PropTypes.string.isRequired
  }

  getChildContext() {
    return { as: this.props.as }
  }

  render() {
    return (
      <div>
        <Item />
      </div>
    );
  }
}
```

**Comment by yesmeck** [comment]
BTW, you can find migration guide [here](https://github.com/erikras/multireducer/releases/tag/v3.0.0-beta2).

**Comment by me6iaton** [comment]
i see, thanks
