### ISSUE TITLE
No more globalDispatch and multireducerKey parameters in v3

### ISSUE THREAD

**Issue by kovcic** [erikras/multireducer#116]
Hello,

why there's no more `globalDispatch` and `multireducerKey` params present in action call at [https://github.com/erikras/multireducer/blob/master/src/wrapDispatch.js#L7](https://github.com/erikras/multireducer/blob/master/src/wrapDispatch.js#L7)?

Is there maybe alternative? Nothing listed in migration guide.

Thx

**Comment by yesmeck** [comment]
It's a bug, could you open a PR?

**Comment by kovcic** [comment]
here you go: https://github.com/erikras/multireducer/pull/117
