### ISSUE TITLE
doc decorators clarification  

### ISSUE THREAD

**Issue by reggi** [erikras/multireducer#7]
Hey @erikras, I'm studying the components in `react-redux-universal-hot-example` like [`CounterButton.js`](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/components/CounterButton/CounterButton.js) and I came across the es7 decorator syntax for the first time. I looked into it, found a great article [here](https://medium.com/google-developers/exploring-es7-decorators-76ecb65fb841). 

I saw that you weren't using that syntax in the readme for this lib. In `STEP 2` you show a different syntax, by passing the component in to the multireducer. I was wondering if you could detail the `@` decorator syntax as well, or were open to a pull, I could take a stab at it. Thoughts?

**Comment by erikras** [comment]
The library is designed with the ES7 syntax in mind. But to keep the docs as simple as possible, I chose to not mention it. However, a section at the end about how to use this library with the decorator syntax would probably be good. :hocho: Stab away! :smile:

**Comment by yesmeck** [comment]
As [v3.0.0](https://github.com/erikras/multireducer/releases/tag/v3.0.0) released, I have removed `connectMultireducer `, so I'm closing this issue.
