### ISSUE TITLE
Use with redux-router

### ISSUE THREAD

**Issue by jmarceli** [erikras/multireducer#8]
Is it possible to provide `multireducerKey` when my container is used as route component in redux-router?

Example (it doesn't work of course):
```
<ReduxRouter>
  <Route path="/orders" component={OrdersList} multireducerKey='orders'/>
  <Route path="/users" component={UsersList} multireducerKey='users'/>
  ...  
 ```

Anything like that is possible or I need to create wrapper page component for my multireducer container?

**Comment by erikras** [comment]
Does redux/react-router pass props down like that? Maybe check in the React devtools to see if the prop is making it all the way to the component. If it is, I don't see why it wouldn't work.

**Comment by jmarceli** [comment]
Unfortunately I didn't find any relevant info in any of the projects (`redux-router`, `react-router`) so I assume it is not possible/supported. Now I'm using wrapper approach but as soon as I find any better solution I'll post it here.

**Comment by jingzhou123** [comment]
+1

**Comment by ntdb** [comment]
I found [this relevant comment from ryanflorence](https://github.com/rackt/react-router/issues/2673#issuecomment-162901440). Perhaps we could customize where multireducer looks for the key inside `props`?

**Comment by yesmeck** [comment]
Hello, I'm working on a [new version](https://github.com/erikras/multireducer/releases/tag/v3.0.0-beta3) of `multireducer`, in the version you can do this:

```javascript
<Route path="/orders" component={OrdersList} as='orders'/>
```

```javascript
const mapStateToProps = (state, { route }) => ({ list: state.listCollection[route.as] })
```

**Comment by yesmeck** [comment]
As [v3.0.0](https://github.com/erikras/multireducer/releases/tag/v3.0.0) released, I'm closing this issue.
