### ISSUE TITLE
load data with multireducer actions for deferredFetch on server

### ISSUE THREAD

**Issue by thecaddy** [erikras/multireducer#97]
I have a multireducer and i want to populate it on the server, not quite sure how to get the actions from the multireduced store.

```
export default combineReducers({
  router: routerStateReducer,
  multireducer: multireducer({
    a: store,
    b: store,
    c: store
  }),
})
```

```
import {load} from 'redux/modules/store'

function fetchDataDeferred(getState, dispatch) {
  //how to load data for multireducer stores
}

@connectData(null, fetchDataDeferred)
class blah extends Component { ... }
```

**Comment by yesmeck** [comment]
Hello, I'm working on a [new version](https://github.com/erikras/multireducer/releases) of `multireducer`, in the new version you can do this:

```javascript
import { wrapDispatch } from 'multireducer'
import { fetch } from './actions'

function fetchDataDeferred(getState, dispatch) {
  return wrapDispatch(dispatch, 'a')(fetch);
}
```

**Comment by yesmeck** [comment]
As [v3.0.0](https://github.com/erikras/multireducer/releases/tag/v3.0.0) released, I'm closing this issue, feel free to reopen this issue if you have any other questions.
